### PR TITLE
Fix/manage buy offer amount attribute

### LINKED ISSUE #138: Unknown attribute 'amount' for Stellar::ManageBuyOfferOp when calling manage_buy_offer
Making a request to the Stellar::Operation.manage_buy_offer prompts an error: Unknown attribute 'amount' for Stellar::ManageBuyOfferOp

The ManageBuyOfferOp struct expects buyAmount https://github.com/astroband/ruby-stellar-sdk/blob/95dedd1a271cbf6f30e9070e3daba04514cf9f07/base/xdr/Stellar-transaction.x#L156
instead of amount attribute which is set here https://github.com/astroband/ruby-stellar-sdk/blob/7638dc1a9b0dbfb2920640ad113fef03e837c4a7/base/lib/stellar/operation.rb#L300

### PR DESCRIPTION
**Pull request by galeamelania**

### CODE REVIEW

File: base/lib/stellar/operation.rb [hunk 1]
```diff
@@ -300,7 +300,7 @@ def manage_buy_offer(attributes = {})
         op = ManageBuyOfferOp.new({
           buying: buying,
           selling: selling,
-          amount: amount,
+          buyAmount: amount,
```
Comment (nebolsin) [inline base/lib/stellar/operation.rb]:
```suggestion
          buy_amount: amount,
```

File: base/spec/lib/stellar/operation_spec.rb [hunk 2]
```diff
@@ -296,3 +296,37 @@
...
+
+RSpec.describe Stellar::Operation, ".manage_buy_offer" do
+  let(:buying_issuer) { Stellar::KeyPair.from_address("GDGU5OAPHNPU5UCLE5RDJHG7PXZFQYWKCFOEXSXNMR6KRQRI5T6XXCD7") }
+  let(:buying_asset) { Stellar::Asset.alphanum4("USD", buying_issuer) }
+
+  let(:selling_issuer) { Stellar::KeyPair.master }
+  let(:selling_asset) { Stellar::Asset.alphanum4("EUR", selling_issuer) }
+
+  it "creates a ManageBuyOfferOp" do
+    op = Stellar::Operation.manage_buy_offer(buying: buying_asset, selling: selling_asset, buyAmount: 50, price: 10)
```
Comment (nebolsin) [inline base/spec/lib/stellar/operation_spec.rb]:
```suggestion
    op = Stellar::Operation.manage_buy_offer(buying: buying_asset, selling: selling_asset, amount: 50, price: 10)
```

We abstract away the underlying XDR verbosity from the SDK user and using `amount` as  parameter name in both buy and sell operation seems a bit cleaner.

File: base/spec/lib/stellar/operation_spec.rb [hunk 3]
```diff
@@ -296,3 +296,37 @@
...
+
+RSpec.describe Stellar::Operation, ".manage_sell_offer" do
+  let(:buying_issuer) { Stellar::KeyPair.from_address("GDGU5OAPHNPU5UCLE5RDJHG7PXZFQYWKCFOEXSXNMR6KRQRI5T6XXCD7") }
+  let(:buying_asset) { Stellar::Asset.alphanum4("USD", buying_issuer) }
+
+  let(:selling_issuer) { Stellar::KeyPair.master }
+  let(:selling_asset) { Stellar::Asset.alphanum4("EUR", selling_issuer) }
+
+  it "creates a ManageSellOfferOp" do
+    op = Stellar::Operation.manage_sell_offer(buying: buying_asset, selling: selling_asset, buyAmount: 50, price: 10)
```
Comment (nebolsin) [inline base/spec/lib/stellar/operation_spec.rb]:
```suggestion
    op = Stellar::Operation.manage_sell_offer(buying: buying_asset, selling: selling_asset, amount: 50, price: 10)
```

File: base/spec/lib/stellar/operation_spec.rb [hunk 4]
```diff
@@ -296,3 +296,37 @@
...
+    expect(op.body.value).to be_an_instance_of(Stellar::ManageSellOfferOp)
+    expect(op.body.value.buying).to eq(Stellar::Asset.alphanum4("USD", buying_issuer))
+    expect(op.body.value.selling).to eq(Stellar::Asset.alphanum4("EUR", selling_issuer))
+    expect(op.body.value.buyAmount).to eq(50)
```
Comment (nebolsin) [inline base/spec/lib/stellar/operation_spec.rb]:
```suggestion
    expect(op.body.value.amount).to eq(500000000)
```

This is "raw" xdr value, so it will be in stroops, not in lumens, and for sell offer it is still `amount`.

File: base/spec/lib/stellar/operation_spec.rb [hunk 5]
```diff
@@ -296,3 +296,37 @@
...
+
+  let(:selling_issuer) { Stellar::KeyPair.master }
+  let(:selling_asset) { Stellar::Asset.alphanum4("EUR", selling_issuer) }
+
+  it "creates a ManageBuyOfferOp" do
+    op = Stellar::Operation.manage_buy_offer(buying: buying_asset, selling: selling_asset, buyAmount: 50, price: 10)
+    expect(op.body.value).to be_an_instance_of(Stellar::ManageBuyOfferOp)
+    expect(op.body.value.buying).to eq(Stellar::Asset.alphanum4("USD", buying_issuer))
+    expect(op.body.value.selling).to eq(Stellar::Asset.alphanum4("EUR", selling_issuer))
+    expect(op.body.value.buyAmount).to eq(50)
```
Comment (nebolsin) [inline base/spec/lib/stellar/operation_spec.rb]:
```suggestion
    expect(op.body.value.buy_amount).to eq(500000000)
```

This is "raw" xdr value, so it will be in stroops, not in lumens. Also in Ruby we use snake case for field names.

File: base/spec/lib/stellar/operation_spec.rb [hunk 6]
```diff
@@ -296,3 +296,37 @@
...
+  let(:selling_issuer) { Stellar::KeyPair.master }
+  let(:selling_asset) { Stellar::Asset.alphanum4("EUR", selling_issuer) }
+
+  it "creates a ManageSellOfferOp" do
+    op = Stellar::Operation.manage_sell_offer(buying: buying_asset, selling: selling_asset, buyAmount: 50, price: 10)
+    expect(op.body.value).to be_an_instance_of(Stellar::ManageSellOfferOp)
+    expect(op.body.value.buying).to eq(Stellar::Asset.alphanum4("USD", buying_issuer))
+    expect(op.body.value.selling).to eq(Stellar::Asset.alphanum4("EUR", selling_issuer))
+    expect(op.body.value.buyAmount).to eq(50)
+    expect(op.body.value.price).to eq(10)
```
Comment (nebolsin) [inline base/spec/lib/stellar/operation_spec.rb]:
```suggestion
    expect(op.body.value.price.to_d).to eq(10)
```

Price here will be an instance of `Stellar::Price` so the direct comparison with 10 will fail.

File: base/spec/lib/stellar/operation_spec.rb [hunk 7]
```diff
@@ -296,3 +296,37 @@
...
+  let(:selling_issuer) { Stellar::KeyPair.master }
+  let(:selling_asset) { Stellar::Asset.alphanum4("EUR", selling_issuer) }
+
+  it "creates a ManageBuyOfferOp" do
+    op = Stellar::Operation.manage_buy_offer(buying: buying_asset, selling: selling_asset, buyAmount: 50, price: 10)
+    expect(op.body.value).to be_an_instance_of(Stellar::ManageBuyOfferOp)
+    expect(op.body.value.buying).to eq(Stellar::Asset.alphanum4("USD", buying_issuer))
+    expect(op.body.value.selling).to eq(Stellar::Asset.alphanum4("EUR", selling_issuer))
+    expect(op.body.value.buyAmount).to eq(50)
+    expect(op.body.value.price).to eq(10)
```
Comment (nebolsin) [inline base/spec/lib/stellar/operation_spec.rb]:
```suggestion
    expect(op.body.value.price.to_d).to eq(10)
```

Price here will be an instance of `Stellar::Price` so the direct comparison with 10 will fail.

**Review by nebolsin — CHANGES_REQUESTED** [review]
Thank you for taking a shot in fixing this and especially for including the specs. There're a couple changes required for those specs to pass, please see my inline comments.

File: base/lib/stellar/operation.rb (hunk 1 above)
Comment (nebolsin) [reply base/lib/stellar/operation.rb]: ✅

**Review by nebolsin — APPROVED** [review]
LGTM 🚀  Thank you for the contribution.
